### ISSUE TITLE
spockframework.org connection is insecure

### ISSUE THREAD

**Issue by danielrehmann** [spockframework/spock#1149] opened 2020-04-23 19:01 UTC
![image](https://user-images.githubusercontent.com/4181010/80138374-051b6180-85a5-11ea-95a3-d832400e81d6.png)
As you can see in the picture above the spock documentation page has no valid encryption and is shown as insecure. This is bad for the spock image. Usually the first thing I do if a want to promote spock to a colleague is sending him a link to this page. A secure page would look much more professional.

**Comment by szpak** [comment] 2020-04-23 19:12
Duplicate of #1004.

**Closed by szpak** 2020-04-23 19:12 UTC

**Comment by danielrehmann** [comment] 2020-04-23 19:23
In my opinion this is a major issue as it has been this way for a long time and will prevent many people from using spock because they got a bad first impression. And browsers become more and more strict so getting to the page becoms a hassle.

**Comment by szpak** [comment] 2020-04-23 19:52
I completely agree. I also feel very uncomfortable with that fact. Please comment in [that issue](https://github.com/spockframework/spock/issues/1004#issuecomment-584783731) if you have proposals how to "fix" it.
