### ISSUE TITLE
NodeInfo#getAnnotation returns instance of Cglib-generated that does not actually implement Annotation

### ISSUE THREAD

**Issue by renatoathaydes** [spockframework/spock#1163] opened 2020-05-15 16:14 UTC
# Issue description

`org.spockframework.runtime.model.NodeInfo#getAnnotation` returns an instance of a generated class which is not implementing `Annotation`, hence it doesn't actually work when it's used as a `ClassCastException` is thrown.

# How to reproduce

In a Spock extension, call `getAnnotation` on a `SpecInfo` instance as shown:

```groovy
Title t = node.getAnnotation( Title )
```

This error will happen (when there's no annotation on the spec, at least):

```
org.spockframework.runtime.model.SpecInfo$$EnhancerByCGLIB$$b2e871b8 cannot be cast to java.lang.annotation.Annotation
```

I would've expected `null` to be returned and there should be no error.

## Java/JDK

```
openjdk version "1.8.0_232"
```

## Groovy version

* Groovy 3.0.1
* Spock 2.0-M2-groovy-3.0

**Comment by Vampire** [comment] 2020-05-15 16:19
Can you maybe provide a minimal reproducer project?
And do you have the same problem when you use ByteBuddy instead of cglib?

**Comment by renatoathaydes** [comment] 2020-05-15 16:19
Ah!! The problem seems to be on a test I have!!! The `SpecInfo` instance was an actual mock! So, what's changed is the mocking done by Spock, not `SpecInfo` itself!

Sorry about the misunderstanding. Not sure if this is still a bug, but I would expect a `Mock` to return null on non-mocked methods?

**Comment by renatoathaydes** [comment] 2020-05-15 16:25
```groovy
package com.athaydes.spockframework.report

import org.spockframework.runtime.model.SpecInfo
import spock.lang.Specification
import spock.lang.Title

class MySpec extends Specification {

    def "my first test"() {
        given:
        def spec = Stub(SpecInfo)

        when:
        def t = spec.getAnnotation(Title)

        then:
        t == null
    }

}
```

This reproduces the problem. It works if I use `Mock` instead.

**Comment by Vampire** [comment] 2020-05-15 16:38
Now I'm a bit confused.
You say in your next to last comment you expect a `Mock` to return `null`.
But in your last comment you show that you use a `Stub` and say with `Mock` it works as expected.
`Mock`s are expected to return 0 or `null` on unmocked methods,
`Stub`s are expectec to do their very best to return some empty or dummy response, so for example `Optional.empty()`, an empty list, an empty array or for non-collections another stub.
This also is not new to 2.0 but is the same since I know Spock.

**Comment by renatoathaydes** [comment] 2020-05-15 16:46
`Mock` and `Stub` should both return `null` for this method in my opinion.

**Comment by renatoathaydes** [comment] 2020-05-15 16:48
This broke my tests after upgrading to 2.0, so I am pretty sure it's new.

**Comment by renatoathaydes** [comment] 2020-05-15 17:01
Ok, just tested with both Cglib and ByteBuddy using Spock version 1.3-groovy-2.5, and they both throw this Exception. Really not sure why my tests had previously been working with that Stub, I suppose it's because the methods being mocked and the methods being called have changed after the Spock upgrade, and somehow this came up...

Closing the ticket as the behaviour is indeed the same as before.

**Comment by Vampire** [comment] 2020-05-15 17:13
You got me slightly wrong and should reopen the issue.
Yes, `Stub` should return a dummy object there, namely another stub.
But it should work properly and not result in a `ClassCastException`.

**Comment by Vampire** [comment] 2020-05-15 17:14
I guess the code thinks this is `Object` return type, not seing the bound on the type parameter and thus producing a wrong stub as return value.

**Comment by leonard84** [comment] 2020-07-03 12:28
Looks like `org.spockframework.mock.runtime.StaticMockMethod#getReturnType` doesn't handle generics with bounds correctly, it just returns `java.lang.Object` here. The code in the whole `org.spockframework.gentyref.*` package is from 2010/13 there is probably more information available in Java 8, at least the `java.lang.reflect#getReturnType` returns `interface java.lang.annotation.Annotation`. Also resolving generics based on method parameters is another task in itself.

**Comment by leonard84** [comment] 2020-07-03 18:44
I've updated the gentyref classes to the latest version and encountered the following problem https://github.com/coekie/gentyref/issues/5

**Closed** 2023-08-11 14:47 UTC
