### ISSUE TITLE
MissingMethodException after update Spock itself to junit-bom:5.6.0-RC1

### ISSUE THREAD

**Issue by szpak** [spockframework/spock#1073] opened 2020-01-13 20:33 UTC
# Issue description
Several own Spock- tests started to fail after upgrade junit-bom from 5.5.2 to 5.6.0-RC1 (master) with:
> groovy.lang.MissingMethodException: No signature of method: static spock.util.EmbeddedSpecRunner.tests() is applicable for argument types: () values: []

It would be good to make Spock junit-5.6 (Platform 1.6.0) compatible.

E.g.
> method name can still contain parentheses
```
Condition failed with Exception:

result.tests().started().list().testDescriptor.displayName == ["an actor (named fred) age 30"]
|      |
|      groovy.lang.MissingMethodException: No signature of method: static spock.util.EmbeddedSpecRunner.tests() is applicable for argument types: () values: []
|      Possible solutions: use([Ljava.lang.Object;), getAt(java.lang.String), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure), wait(), wait(long)
|      	at org.spockframework.smoke.parameterization.UnrolledFeatureMethods.method name can still contain parentheses(UnrolledFeatureMethods.groovy:320)
<spock.util.EmbeddedSpecRunner$SummarizedEngineExecutionResults@314708ce results=org.junit.platform.testkit.engine.EngineExecutionResults@50706160>

	at org.spockframework.smoke.parameterization.UnrolledFeatureMethods.method name can still contain parentheses(UnrolledFeatureMethods.groovy:320)
Caused by: groovy.lang.MissingMethodException: No signature of method: static spock.util.EmbeddedSpecRunner.tests() is applicable for argument types: () values: []
Possible solutions: use([Ljava.lang.Object;), getAt(java.lang.String), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure), wait(), wait(long)
	... 1 more
```

All the tests seem to be related to parameterization.

# How to reproduce
Bump junit-bom to `"org.junit:junit-bom:5.6.0-RC1"` and call `gw check`.

# Additional Environment information
OpenJDK 11.0.5, Linux, spock from master

# Additional information

```
Failed tests

    FeatureMethods. are nevertheless reported with their original name
    FeatureMethods. can have names containing any characters in embedded specs
    PendingFeatureExtensionSpec. @PendingFeature includes reason in exception message
    RequiresExtension. verifyExecution
    DataTables. cell references are evaluated correctly in the method's name
    UnrolledFeatureMethods. can unroll a whole class at once
    UnrolledFeatureMethods. expressions in naming pattern that can't be evaluated are prefixed with 'Error:'
    UnrolledFeatureMethods. if creation of a data provider fails, feature isn't unrolled
    UnrolledFeatureMethods. iterations of an unrolled feature foo are named foo[0], foo[1], etc.
    UnrolledFeatureMethods. method name can act as naming pattern
    UnrolledFeatureMethods. method name can still contain parentheses
    UnrolledFeatureMethods. method-level unroll annotation wins over class-level annotation
    UnrolledFeatureMethods. naming pattern in @Unroll annotation wins over naming pattern in method name
    UnrolledFeatureMethods. naming pattern may refer to data variables
    UnrolledFeatureMethods. naming pattern may refer to feature name and iteration count
    UnrolledFeatureMethods. naming pattern supports property expressions
    UnrolledFeatureMethods. naming pattern supports zero-arg method calls
    UnrolledFeatureMethods. variables in naming pattern whose value is null are replaced correctly
```

**Comment by leonard84** [comment] 2020-01-13 21:05
This is caused by the deprecation of said method in `EngineExecutionResults` and the behavior of `@Delegate`, by default it does not delegate deprecated methods. The quick fix would be to set `@Delegate(deprecated=true)` in `spock.util.EmbeddedSpecRunner.SummarizedEngineExecutionResults`. The correct fix is to replace all usages of `tests()` by `testEvents()` and so on, see the deprecation notes for more information.

**Comment by leonard84** [comment] 2020-02-10 21:52
Spock-2.0-M2 was just released with the quickfix

**Closed** 2020-03-24 23:20 UTC
Labels: enhancement, junit-platform

**Comment by henrik242** [comment] 2020-04-21 07:38
@leonard84  @szpak  `EngineExecutionResults` is still referenced here:

- https://github.com/spockframework/spock/blob/7aaffbf4fc426ac60a7b38324493a9ee946266d9/spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy#L136 - https://github.com/spockframework/spock/blob/ab18243c4ea4d33369801eab2f79cfe5b0766b0a/spock-testkit/src/test/groovy/spock/platform/SpockHelloWorldTest.java#L96
- https://github.com/spockframework/spock/blob/7aaffbf4fc426ac60a7b38324493a9ee946266d9/spock-core/src/main/groovy/spock/util/EmbeddedSpecRunner.groovy#L152

This gives me `Caused by: groovy.lang.MissingMethodException: No signature of method: spock.util.EmbeddedSpecRunner.runWithImports() is applicable for argument types: (String) values: ...` --> `java.lang.NoClassDefFoundError: org/junit/platform/testkit/engine/EngineExecutionResults`

**Comment by szpak** [comment] 2020-04-21 08:31
@henrik242 Hmm, this class seems to be available in master of JUnit 5:
https://github.com/junit-team/junit5/blob/master/junit-platform-testkit/src/main/java/org/junit/platform/testkit/engine/EngineExecutionResults.java

Please paste your dependencies.

**Comment by henrik242** [comment] 2020-04-21 08:45
@szpak Thanks, that was it! I had to manually add the `org.junit.platform:junit-platform-testkit` dependency.   Should that maybe be a transitive dependency of `spock-core`?

**Comment by szpak** [comment] 2020-04-21 09:09
Ok, you seem to run some tests with `EmbeddedSpecRunner`. `junit-platform-testkit` is defined as an optional dependency:
>   compile libs.junitPlatformTestkit, optional

Therefore, you need to add it manually. It's not the a regular cases, however, I agree it is not very intuitive. Would you like to propose an improvement in the documentation (both regular documentation and release notes) to cover it?

**Comment by henrik242** [comment] 2020-04-21 09:19
@szpak It was especially difficult to figure out since I only saw the `MissingMethodException`.  The `NoClassDefFoundError` was hidden until I debugged and tried `EmbeddedSpecRunner().class.declaredMethods`.   So if `junit-platform-testkit` has to stay optional, spock should at least try to output an error that explains this (or makes debugging easier).

**Comment by Vampire** [comment] 2020-04-21 09:29
@szpak I guess this should be rather easy to improve, especially as the runner is written in Groovy?
If you replace the `EngineExecutionResults` occurrences by duck-typing, it is not missing anymore.
Then the left problem is that `EngineTestKit` is missing.
But that is not part of any method signature, so you shouldn't get any missing method exception, but hopefully a meaningful error that that class is not found.

Maybe even better like we warn meaningfully about missing Objenesis and so on, would be to then check in `doRunRequestInner` whether the `EngineTestKit` class is present and otherwise give a meaningful warning that suggests the dependency that is missing. wdyt?

**Comment by szpak** [comment] 2020-04-21 09:29
We could try to detect the missing class by reflection, but it could be tricky. Could you create a new issue to try to cover it?

And still, if you have some time, please provide a PR with documentation improvements (to have at least that for now :) ).

**Comment by szpak** [comment] 2020-04-21 09:32
@Vampire I was thinking about something like that with reflection in my previous message sent in the same time as your :-).

**Comment by henrik242** [comment] 2020-04-21 09:46
Yup, I guess fixing those signatures would improve the error message.  That said, are you planning to release another milestone (or even RC) any time soon? 4 months since the last one, would have been awesome to not depend on a SNAPSHOT 😄

**Comment by szpak** [comment] 2020-04-21 09:52
4 months? :-)
> spock-2.0-M2
> on Feb 10 d551442

There is a plan to release M3 "soon" with (in majority) the great set of changes made by @Vampire related to unrolling.

**Comment by henrik242** [comment] 2020-04-21 09:54
>  @henrik242 Could you create a new issue to try to cover it?

Yup: https://github.com/spockframework/spock/issues/1148

> 4 months? :-)

Ooops, sorry. I believe I saw December 15th or something somewhere.  I'm probably delusional from too much home office. ;)

**Comment by henrik242** [comment] 2020-04-21 10:12
> 4 months? :-)
> 
> > spock-2.0-M2
> > on Feb 10 [d551442](https://github.com/spockframework/spock/commit/d55144254f8e2b48af1968de0a7c78a31b5da815)

Ah, found it in README.md:

`The latest 2.0 release version is 2.0-M2 (2.0-M2-groovy-2.5, 2.0-M2-groovy-3.0), released on 2019-12-31.`

**Comment by szpak** [comment] 2020-04-21 10:42
Thanks, I will fix it.

**Comment by Vampire** [comment] 2020-04-21 10:49
> There is a plan to release M3 "soon" with (in majority) the great set of changes made by @Vampire related to unrolling/parameterize tests.

Where "soon" depends on JUnit releasing 5.7.0 first.

**Comment by szpak** [comment] 2020-04-21 12:28
M3 is not a final release, it might depend on another milestone :).
