### ISSUE TITLE
StackOverflowError when mocking generics

### ISSUE THREAD

**Issue by vprudnikov** [spockframework/spock#1971] opened 2024-07-11 11:54 UTC
### Describe the bug

Starting with `2.4-M2-groovy-4.0`, generics are not handled properly. However, the version `2.4-M1-groovy-4.0` works fine.

### To Reproduce

```
import org.springframework.hateoas.RepresentationModel;

public class Impl {

    private final InnerInterface inner;

    Impl(InnerInterface inner) {
        this.inner = inner;
    }

    void method() {
        inner.method();
    }

    interface InnerInterface {
        <T extends RepresentationModel<T>> T method();
    }
}
```

```
class ImplSpec extends Specification {

    Impl.InnerInterface inner = Mock()

    def "Method can be called"() {
        given:
        def impl = new Impl(inner)

        when:
        impl.method()

        then:
        noExceptionThrown()
    }
}
```

### Expected behavior

The test succeeds.

### Actual behavior

```
Expected no exception to be thrown, but got 'java.lang.StackOverflowError'

	at spock.lang.Specification.noExceptionThrown(Specification.java:123)
	at no.apotek1.javalibs.refprojects.ImplSpec.Method can be called(ImplSpec.groovy:17)
Caused by: java.lang.StackOverflowError
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
...
```

### Java version

21.0.3

### Buildtool version

maven 3.9.6

### What operating system are you using

Windows

### Dependencies

```
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-spring</artifactId>
            <version>${spock.version}</version>
            <scope>test</scope>
        </dependency>
```

**Comment by AndreasTu** [comment] 2024-07-11 15:42
Duplicate of #1909

**Closed by AndreasTu** 2024-07-11 15:42 UTC
Labels: bug
