### ISSUE TITLE
Improve documentation regarding optional dependencies

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock#1165] opened 2020-05-19 01:56 UTC
Currently there is a small section hidden somewhere in the middle of the manual, mentioning optional dependencies like CGLIB, ByteBuddy and Objenesis. I think they belong into a "Build prerequisites" section rather at the top of the user manual. I also believe it would be possible to better explain which dependency does what, especially with regard to the "either-or" between CGLIB and ByteBuddy. They overlap in functionality. Which one is recommended for which case? Why maintain two ways to mock classes? There must be a unique benefit to each library in specific cases. But which one?

One idea is to organise this as a matrix (table) with columns "tool" (containing name in plain prose and Maven/Gradle coordinates with minimal or suggested version) and "purpose" (containing bullet points explaining what the library does and when to add it to the project).

If you think this is too technical for a user manual, you can link off to a "technical background" document, but I think it belongs in the user manual because every user first needs to set up her Maven or Gradle project before starting to learn about "given - when - then" and even be able to run tests in the first place.

**Comment by leonard84** [comment] 2020-08-26 17:16
`cglib` or `byte-buddy` are not required and spock can work fine without them, they are only necessary when you want to mock classes and not just interfaces. In which case spock will notify you that you need one of those libraries. `objenesis` is also only necessary when the class has no default constructor.

To answer the question why we support two libraries, it is backwards compatibility. `cglib` was first, then `byte-buddy` was added later and also becoming the preferred library. As this area requires rather low maintenance effort we didn't feel the need to remove `cglib` support. And without telemetry data it is impossible to say how many users would be affected.

**Comment by kriegaex** [comment] 2020-08-27 00:16
> `cglib` or `byte-buddy` are not required and spock can work fine without them, they are only necessary when you want to mock classes and not just interfaces. In which case spock will notify you that you need one of those libraries. `objenesis` is also only necessary when the class has no default constructor.

I know, hence the issue subject "Improve documentation regarding _**optional**_ dependencies". Still I would additionally add them to the "build prerequisites" section and just suddenly mention them in the middle of the manual (where of course they belong too in context), because most users reading the manual are just eager to get started and at the beginning do not understand the fine details of interfaces vs. classes or classes with vs. without default constructors. They just want to start using Spock and "mock stuff". Your explanation above or something similarly enlightening and concise would do nicely in the manual. A tiny bit of redundancy would be in order, I think. I am not confident to provide a PR after my experience with the one you merged yesterday after a rather painful process. Maybe it is better if you just write it exactly the way you like it after us talking here.

> To answer the question why we support two libraries, it is backwards compatibility. `cglib` was first, then `byte-buddy` was added later and also becoming the preferred library. As this area requires rather low maintenance effort we didn't feel the need to remove `cglib` support. And without telemetry data it is impossible to say how many users would be affected.

Thank you so much for the explanation, now I understand. :-) This would also be helpful for users to read in the manual in order for them to understand. Most of them probably would not dig deep enough and do a full text search in the issues section in order to find your explanation here. The manual is great already with regard to its content, but a little bit of story-telling could help the cohesion and could help on-board new users. It is always a good feeling to not just know the "what" and "how to" but also the "why", because the latter is what makes people confident they understand what they are doing something.

**Comment by leonard84** [comment] 2020-08-27 11:27
The problem is time, I can do either development or improve the documentation. 

Furthermore, there are four different types of documentation:

![https://documentation.divio.com/](https://user-images.githubusercontent.com/1151511/91424257-dc102380-e859-11ea-82f9-70d4741128d4.png)
Source https://documentation.divio.com/ 

I can highly recommend the [video](https://www.youtube.com/watch?v=t4vKPhjcMZg), that explains this.

The current guide is already a mixture of the different types, adding more explanations to it would further increase the technical debt. What you are describing, probably belongs in a dedicated `How-To get started with Spock` and maybe even a tutorial and the explanation with regards to cglib/bytebuddy part belongs in a separate section as well. 

I'm not sure how to refactor the documentation so that it better fits into these types, and also where to put it, but that discussion probably belongs in a dedicated issue.

I'm sorry that you feel disheartened after your last PR, it is not my intention to discourage contributors by providing feedback in the reviews. At the end of the day we are a rather small team of active contributors (2-3), who do so in their spare time. We are happy for every willing contributor. In some cases a prior discussion in an issue would have avoided rejected PRs. And sometimes PRs need lots of work, e.g., #1199 had almost 150 comments and 42 commits, but was successfully merged at the end (this was an extreme case though). 

I see you are already very active on stackoverflow thanks for that, but if you also want to help out improving the documentation I can invite you to our slack channel, where discussing something like this might be faster.

**Comment by kriegaex** [comment] 2020-08-28 03:10
Feel free to close the issue.

You say you do have not enough time for programming. OTOH you seem to have lots of time for endless debates in issues and PRs. In the time we have talked here, you could easily have added two helpful sentences to the manual instead of obsessing about types of documentation. Why not improve the existing documentation instead of theorising about a separate document which could contain more information? If in the future you ever create such a document, you can still refactor the Spock manual, moving parts into the new document. But what I like so much about the Spock manual today is that I can find almost all information in one document, because it simply makes on-boarding or searching for reference information easier and quicker. 

You are really making it hard to contribute anything to this project and not getting disheartened. I feel like I am wasting my time, trying to contribute.

Thanks for the invitation to the Slack channel, I am feeling honoured. I never used Slack before, though, so I do not have an account there. I am in the Gitter channel already and will consider joining Slack, but AFAIK it is not free. At least it was not when I tried last time. Before trying to join Slack, I will think about whether it makes sense or not for me personally because my experience here was so frustrating.

**Comment by Vampire** [comment] 2020-08-28 11:58
We are very grateful for your contributions, especially your SO activity.

But please realize as you could also have observed in our previous conversations, that not everyone shares your or Scrums idea of how software development should be done. Obviously Leonard and me are more the kind that first think about what to do and how to do it properly instead of the rapid-prototyping guy you are.

You may unfortunately be discouraged to post any further PRs due to the Travis problem or whatever, but please be a bit nicer here and accept the difference of methodology other developers are following. We also do this in our sparse spare time and and posts like the one you just did here can easily lower the mood to do anything and thus is more counter productive than anything else.

> and will consider joining Slack, but AFAIK it is not free

For you it will be free either way.
For the one driving the Slack, it could cost.
But there is a free plan Spock uses.
Just if you need to search more than the last 10k messages or need more than 10 integrations and similar you have to upgrade to a paid plan.
But even then it will not cost you a buck. :-)

**Comment by kriegaex** [comment] 2020-08-29 07:29
> not everyone shares your or Scrums idea of how software development should be done. Obviously Leonard and me are more the kind that first think about what to do and how to do it properly instead of the rapid-prototyping guy you are.

Allegation no. 1: Scrum guys (especially me) just produce prototypes and don't think before doing work.

> posts like the one you just did here can easily lower the mood to do anything and thus is more counter productive

Allegation no. 2:  It was me killing the mood, not the people communicating with me in a way that I felt was nitpicking and a wee bit condescending. So it is my own fault that I feel disheartened and demotivated.

---

> > and will consider joining Slack, but AFAIK it is not free
> 
> For you it will be free either way.

I did not know that because I only see Slack from outside and it wants me to buy a plan when signing up. So probably if you invite me, it will be different, which is nice. Just send me a personal message on Gitter, telling me which data you need in order to invite me or create a user account on my behalf. Thank you, Björn.

**Comment by Vampire** [comment] 2020-08-29 12:16
> Allegation no. 1: Scrum guys (especially me) just produce prototypes and don't think before doing work.

I just derived that from your statement, as you requested this from Leonard. Summarized you said "stop wasting time with theorizing, obsessing, talking and thinking about how to do it, just do it like I suggested without thinking". At least that is what arrived on our sides of the communication channel. ;-)

> Allegation no. 2:  It was me killing the mood, not the people communicating with me in a way that I felt was nitpicking and a wee bit condescending. So it is my own fault that I feel disheartened and demotivated.

It was not my intention to be condescending and I'm pretty sure also not Leonards. Also I didn't say it is your fault that you feel demotivated. I just tried to tell you, that you are demotivating others if you tell them things like "you are wasting your time with your methodology, use mine instead", "you are obsessed" or always twisting the words of your communication partners, as I assumed and hoped that was not your intention.

> I did not know that because I only see Slack from outside and it wants me to buy a plan when signing up.

Does it? Interesting. Maybe the local version in the country you are is different. If I go to slack in a private tab, I'm offered to either login into an existing workspace or create one for free and the pricing page also starts with the free plan.

The registration / login process of Slack is a bit strange though sometimes, yes. Basically for every workspace you re-register and in each device where you use Slack you have to manually add the workspaces you want. That always feels a bit clunky to me, instead of just creating a login and have all workspaces available to which you gain access.

I'm sure Leonard will send you an invitation soon and I got you will be able to create a free account then.

**Comment by kriegaex** [comment] 2020-08-30 02:41
> > Allegation no. 1: Scrum guys (especially me) just produce prototypes and don't think before doing work.
> 
> I just derived that from your statement, as you requested this from Leonard.

No, you interpreted something _into_ my statement that I never said or meant.

And please, Björn, spare me your rabulistic replies. I appreciate you so much as a developer and you are also a very nice guy, I noticed that during our private chats. But you are the prototype of a rabulist, conveniently interpreting, omitting, twisting arguments to make things turn out the way you like them to be. It is not so much fun to have a debate like this because it feels like it is not about making progress, achieving consensus or acknowledging someone else's ideas, but more about doing things your style and your style only. Progress or improvements can be achieved in different ways, I kindly request you to acknowledge that. And despite my criticism here I will always be open to further collaborate you and of course also with Leonard. The Spock team is lucky to have you both.

**Closed** 2020-09-08 20:47 UTC
