### ISSUE TITLE
Spring Boot 1.4 @WebMvcTest support

### ISSUE THREAD

**Issue by alexejk** [spockframework/spock#624] opened 2016-07-26 11:54 UTC
Support for `@SpringTest` has been added as part of #581 , however this only provides basic functionality and does not allow to utilise the power of Spring Boot 1.4 and it's testing enhancements in a complete way.

Basic Web MVC Test for a controller without any dependencies that need to be `@Autowired` will go through. Spring framework 4.3 provides constructor injection enhancements and even prior to 4.3 it's recommended to use constructor injection for component dependencies. `@WebMvcTest` when used with JUnit/Mockito empowers developer to automatically inject mock beans with help of new `@MockBean` annotation.

This naturally does not work with Spock and mocks created via Spocks `Mock()` are not injected into the constructor as dependencies, making it much harder to work with Spring Boot and Web MVC Tests.

**Comment by kamaydeo** [comment] 2016-08-05 16:05
+1 for @MockBean support.

**Comment by lavcraft** [comment] 2016-08-07 19:00
And @SpyBean support was needed too

**Comment by leonard84** [comment] 2016-08-17 15:40
Duplicates `@MockBean` and `@SpyBean` Issue #629

**Comment by AlexejK** [comment] 2016-08-18 06:25
Technically it's the other way around (this one has been open for 2weeks longer) but yes -  They are about the same problem.

**Comment by leonard84** [comment] 2016-08-18 08:18
@AlexejK yes, but the title of the other one reflects the issue better and it has an example ;)

**Comment by AlexejK** [comment] 2016-08-18 09:20
One thing I believe that issue does not reflect is the bean injection  especially within webmvc tests where as of new spring version, constructor injection happens automatically. 

The #629 issue attempts to use mockito specific annotation which shouldn't logically work,  but this issue in fact that there is no way to provide spring with information about spock mocks so it can do injection. 

With this said,  I no longer believe it's a duplicate, even though they are touching similar subjects.

**Comment by lavcraft** [comment] 2016-08-18 09:37
@AlexejK yes, I used spring boot mockito annotation. But i will use similar Spock annotations for spring boot test if it exists

**Comment by leonard84** [comment] 2016-08-18 10:00
@AlexejK as I already said in #629 the upcoming version of spock lets you create mocks outside the context of a specification, e.g. in an application context, so they can get injected.

**Comment by snekse** [comment] 2016-08-18 14:50
@leonard84 I tried the suggested config detached mock, but on a `@WebMvcTest`, it prevents `MockMvc` from being injected into the spec.

`NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.test.web.servlet.MockMvc] `

If I remove `loader=AnnotationConfigContextLoader`, then the `MockMvc` gets wired correctly. 

Granted, my tests still aren't working correctly because it seems like it doesn't want to pick up my interaction definitions, but I'm still investigating that.

**Comment by leonard84** [comment] 2016-08-19 11:41
@snekse could you provide a [SSCCE](http://www.sscce.org/)

**Comment by snekse** [comment] 2016-08-19 16:37
How's this?

https://github.com/snekse/spock-webmvctest

**Comment by kiview** [comment] 2016-08-19 18:32
What do you think about introducing a new Spock-specific annotation (`@SpockWebMvcTest`), which will duplicate the behaviour of `@WebMvcTest` but with Spock Mocks? This would be kind of hackish, but we'd have a solution.

**Comment by leonard84** [comment] 2016-08-19 19:15
@snekse this missing `{lang}` was the main issue and it seems that `AnnotationConfigContextLoader` does not work well with `@WebMvcTest`, however it works fine if you just remove it.

```patch
Index: src/test/groovy/org/spockframework/controllers/GreetingControllerDetachedFactoryTest.groovy
===================================================================
--- src/test/groovy/org/spockframework/controllers/GreetingControllerDetachedFactoryTest.groovy	(revision 7325006cb2386bd56cdf600e38fbc1b3a81056ef)
+++ src/test/groovy/org/spockframework/controllers/GreetingControllerDetachedFactoryTest.groovy	(revision )
@@ -29,7 +29,7 @@
  *
  * @see GreetingNoDependencyControllerTest
  */
-@ContextConfiguration(loader=AnnotationConfigContextLoader)
+@ContextConfiguration
 @WebMvcTest(GreetingController)
 class GreetingControllerDetachedFactoryTest extends Specification {
 
Index: src/main/groovy/org/spockframework/controllers/GreetingController.groovy
===================================================================
--- src/main/groovy/org/spockframework/controllers/GreetingController.groovy	(revision 7325006cb2386bd56cdf600e38fbc1b3a81056ef)
+++ src/main/groovy/org/spockframework/controllers/GreetingController.groovy	(revision )
@@ -14,7 +14,7 @@
     @Autowired GreetingService greetingService
 
     @SuppressWarnings("GrMethodMayBeStatic")
-    @GetMapping(path = "/")
+    @GetMapping(path = "/{lang}")
     String greetWorld(@PathVariable String lang) {
         return greetingService.greet(lang)
     }
```

**Comment by snekse** [comment] 2016-08-19 20:44
Doh. That's what I get making changes late stages.  The injection is indeed working properly.  I'll update my project to reflect the proper way.

**Comment by kiview** [comment] 2016-08-19 21:07
It's kind of a bug, that we still have to provide the `@ContextConfiguration` in order for Spock to identify the test as an integration test. I thought I've caught all cases in this #610, but the support for this annotation is obviously missing on multiple levels.

Since it seems we need some special code for handling `@WebMvcTest`, I might be able to implement some code which will automatically create the needed `Beans` using a `DetachedMockFactory`, what do you think about this?

**Comment by leonard84** [comment] 2016-08-19 23:18
Yes #610 is not part of rc-1, it is part of rc-2 which should have been published, but there are issues with sonatype.

As for the other part, it depends on the complexity. Looking at https://github.com/spring-projects/spring-boot/tree/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito there is a whole lot of stuff going on. I'm not convinced that the complexity is worth it, and keep in mind that it needs to be backwards compatible to the existing code base.

Although it is a bit more ceremony compared to `@MockBean` it is still rather simple and if you put the factory in a base class then it's just the `@Bean` declaration.
```groovy
  static class Config {
        private DetachedMockFactory factory = new DetachedMockFactory()

        @Bean
        GreetingService greetingService() {
            factory.Mock(GreetingService, name:"greetingService")
        }
    }
```

**Comment by kiview** [comment] 2016-08-19 23:44
I agree, The _spock-spring_ module is already kind of cluttered in order to stay mostly backwards compatible, looking for lot's of different annotations and stuff.

I think this is the class which functionality we'd need to replicate:
[MockitoPostProcessor](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-test/src/main/java/org/springframework/boot/test/mock/mockito/MockitoPostProcessor.java)

We should also think about the rarity of defining Stubs/Mocks without specified behavior (which is what the spring implementation mainly does). So if we'd try to come up with a truly useful solution we'd need some way to specify the intended behavior as well.

However I'd like to document your proposed approach of using a `DetachedMockFactory` and `@Bean`  definition somewhere. Maybe we can even update the _spring-boot_ documentation itself to include this workaround (there is already a tiny paragraph about _Spock_ in the official documentation).

**Comment by leonard84** [comment] 2016-08-20 01:52
@kiview more documentation is always good. You could also extend the boot-test project to include an example Spec.

Spock uses AST rewriting to have the powerful mock behavior dsl, the problem with that is that it requires the closure source to be in the context of the `Specification`. You can't just apply any closure to the mock object. And Spock mocks don't work outside of a `Specification`, with the `DetachedMockFactory` they can be created outside but they can't have any behavior until they are attached to a `Specification`.

**Comment by snekse** [comment] 2016-08-20 03:01
If I could write a spec how I normally write specs, but annotate the class like `@SpockSpringBeans(classes=[FooService,BarService])`, that would be pretty cool. 

_Imagining that annotation would basically just be defining a config to be used and the classes it would mock with the detached factory. Then all of the interaction closures would be defined in the spec just like all of my other specs._

**Comment by kiview** [comment] 2016-08-20 12:34
@snekse I think that's how Grails does it as well (at least they did it like this in version 2.x), I'm not sure what happens if you use Spock with Grails, maybe they already have some code for this functionality? It might be a good idea to look into Grails' mocking facilities.

**Comment by leonard84** [comment] 2016-08-20 13:05
It looks like they use their own mocking implementation for `@Mock(..)`. The only example with Spock mocks was this.
```groovy
@FreshRuntime
@TestMixin(GrailsUnitTestMixin)
class MockedBeanSpec extends Specification {
    def myService=Mock(MyService)

    def doWithSpring = {
        myService(InstanceFactoryBean, myService, MyService)
    }

    def "doWithSpring callback is executed"() {
        when:
        def myServiceBean=grailsApplication.mainContext.getBean('myService')
        myServiceBean.prova()
        then:
        1 * myService.prova() >> { true }
    }
}
```
Here they manually construct the service bean in `doWithSpring `.

**Comment by snekse** [comment] 2016-08-23 20:15
Just throwing in a bit of an update.  My example doesn't include security and for some reason, some of the things we were doing would whack MVC mappings when using the `@Configuration static class Config`.  We would get 404 errors despite knowing the mapping existed.

I was able to resolve this by pulling the config outside of the spec and `@Import(MySpecConfig)`

We're still using the `DetachedMockFactory`, so everything inside the spec looks like a basic unit test.

**Comment by leonard84** [comment] 2016-08-23 20:27
Any idea why `@Configuration` breaks things, kinda sounds like a spring boot bug?

**Comment by knizamov** [comment] 2016-08-27 17:06
@snekse @leonard84 http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications-detecting-config

> If you want to customize the primary configuration, you can use a nested @TestConfiguration class. Unlike a nested @Configuration class which would be used instead of a your application’s primary configuration, a nested @TestConfiguration class will be used in addition to your application’s primary configuration.

Try changing nested `@Configuration` to `@TestConfiguration`.

**Comment by kiview** [comment] 2016-08-29 11:26
@leonard84 I've talked with someone from the Pivotal Spring-Boot team at the weekend and he suggested as well, that we do an implementation which is similar to the `MockMvcBean` annotation and provide a custom Spock annotation.

**Comment by leonard84** [comment] 2016-08-29 18:13
@kiview this could be implemented as an extra module/extension, since it does not require changes to Spock itself to work. And this way it would be easier to only support newer spring versions.

**Comment by kiview** [comment] 2016-08-29 19:35
@leonard84 I think we could do it like this, dropping backwards compatibility seems like a huge boon. So do you think we should add a new module to Spock, or should I create a new repository for this?

**Comment by kiview** [comment] 2016-08-29 21:23
@knizamov If uploaded a working example using `DetachedMockFactory` and `@TestConfiguration` on my Github Profile:
https://github.com/kiview/spring-spock-mock-beans-demo/tree/master

**Comment by leonard84** [comment] 2016-08-29 22:38
@kiview I would put it in a separate repo for now, similar to https://github.com/marcingrzejszczak/spock-subjects-collaborators-extension. This way it can follow the faster spring boot release cycles.

**Comment by leonard84** [comment] 2016-08-30 00:16
@kiview I've added a little more documentation to the spring module in PR #641 with an example for `@WebMvcTest` as well. Any comments?

**Comment by kiview** [comment] 2016-08-30 07:06
@leonard84 The documentation looks really useful. Maybe we can even link to the docs from inside the Spring-Boot docs (there is a tiny Spock chapter after all), once the PR has been merged.

Regarding the extension:
Alright, then I'll start on developing a new Spock extension in a new repository in the following days.

**Comment by sofiaguyang** [comment] 2017-05-29 14:57
The suggested way of creating an @Bean of a mock only works if you want to provide a mock bean. But suppose you want to replace an existing bean with a mock (and you don't want the existing bean's definition to trigger at all), that's what `BeanFactoryPostProcessor`/`MockitoPostProcessor`  does. I created a [TestDoubleInjector](https://gist.github.com/sofiaguyang/05f6153e5c87cb6df5de2bd643515b69) which works with Spock mocks. Thinking of creating an annotation-based version of this to mimic how one would use  `@MockBean`.

**Comment by leonard84** [comment] 2017-05-29 15:57
@twicksell is experimenting with adding Mockito-like `@MockBean` support to Spock. 

In the meantime, if you create a mock bean in a `@TestConfiguration` with the same id as the original bean, then it should override it.

**Comment by pchudzik** [comment] 2017-07-25 06:04
Hi guys i just wanted to let you know that I've jsut released springmock library. With springmock you can inject spock mocks into spring integration Specifications.

More [on my blog](https://blog.pchudzik.com/201707/springmock-v1/) and on the [project github page](https://github.com/pchudzik/springmock)

**Comment by leonard84** [comment] 2017-12-10 22:45
Annotation based mock support is coming with #796. please review and add comments
@alexejk @pchudzik @kiview @snekse @lavcraft @kamaydeo

**Comment by leonard84** [comment] 2017-12-22 16:53
Closing, implemented with #796

**Closed by leonard84** 2017-12-22 16:53 UTC

**Comment by fernandocamargoti** [comment] 2018-02-12 12:13
@leonard84, when is it going to be released?

**Comment by leonard84** [comment] 2018-02-12 16:57
@fernandocamargoti have you tried the snapshot/jitpack builds yet? We need some more testers
