### ISSUE TITLE
`PollingConditions` can't assert when declare its field with `def` type

### ISSUE THREAD

**Issue by chenxi-null** [spockframework/spock#1043] opened 2019-10-17 02:13 UTC
# Issue description
`PollingConditions` can't assert when declare field with `def` type, 
while it works when declare it with `PollingConditions` type.

# How to reproduce
```java
import groovy.util.logging.Slf4j
import org.spockframework.runtime.SpockTimeoutError
import spock.lang.Specification
import spock.util.concurrent.PollingConditions

@Slf4j
class PollingConditionsTest extends Specification {

    // doesn't work
    def conditionsWithDef = new PollingConditions()

    // works
    PollingConditions conditionsWithFullClassName = new PollingConditions()

    // this test case if failed, `PollingCondition` failed to assert false condition
    def "global scope: declared with `def`"() {
        when:
        log.info(">>> start")
        conditionsWithDef.within(1, { false })
        log.info("<<< end")
        then:
        thrown(SpockTimeoutError)
    }

    def "global scope: declared with Full class name"() {
        when:
        conditionsWithFullClassName.within(1, { false })
        then:
        thrown(SpockTimeoutError)
    }

    def "local scope"() {
        when:
        new PollingConditions().within(1, { false })
        then:
        thrown(SpockTimeoutError)
    }
}
```

Here is log:
```
10:05:23.916 [main] INFO com.chenxi.demo.spock.PollingConditionsTest - >>> start
10:05:23.932 [main] INFO com.chenxi.demo.spock.PollingConditionsTest - <<< end
```
Only 2 mills elapsed!   
Maybe this method `PollingConditions#within` isn't executed at all.

## Java/JDK
1.8.0_181

## Groovy version
2.5.8

### Apache Maven
3.5.4 

## Operating System
Mac

## IDE
IntelliJ

### Apache Maven
```xml
<dependency>
    <groupId>org.spockframework</groupId>
    <artifactId>spock-core</artifactId>
    <version>1.3-groovy-2.5</version>
</dependency>
```

**Comment by leonard84** [comment] 2020-01-10 23:12
Although it was posted first, more discussion happened in the other ticket so I'll mark this one as duplicate of #1054

**Closed by leonard84** 2020-01-10 23:12 UTC
Labels: duplicate
