### ISSUE TITLE
surefire.skipAfterFailureCount doesn't work

### ISSUE THREAD

**Issue by fenuks** [spockframework/spock#1568] opened 2023-02-01 12:04 UTC
### Describe the bug

Maven surefire plugin [has option](https://maven.apache.org/surefire/maven-surefire-plugin/examples/skip-after-failure.html) to skip tests after given number of test failures. It doesn't seem to work with spock.

### To Reproduce

Clone official [spock-example repo](https://github.com/spockframework/spock-example), introduce error in any test, and then run

```sh
mvn test -Dsurefire.skipAfterFailureCount=1
```

### Expected behavior

Remaining tests should be skipped after first failure.

### Actual behavior

All tests are being run.

### Java version

openjdk 11.0.18 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10)
OpenJDK 64-Bit Server VM (build 11.0.18+10, mixed mode)

### Buildtool version

Maven home: /opt/maven
Java version: 11.0.18, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk
Default locale: pl_PL, platform encoding: UTF-8
OS name: "linux", version: "6.1.8-arch1-1", arch: "amd64", family: "unix"

### What operating system are you using

Linux

### Dependencies

Same as spock-example repo.

**Comment by Vampire** [comment] 2023-02-02 13:52
That's not so much an issue of Spock.
That Surefire flag only supports JUnit 4 for now, so it worked with Spock 1.x.
But Spock 2.x is a JUnit 5 engine and even Jupiter is not supported.

See https://github.com/junit-team/junit5/issues/1880 and https://issues.apache.org/jira/browse/SUREFIRE-1710.

So either JUnit 5 has to add some capability that works for the Spock engine too and Surefire uses it, or Surefire needs to add explicit support for Spock providing a Spock extension that provides this behavior.

In the meantime, you could as well use a Spock extension that provides the behavior. Should not be too hard to implement a global Spock extension that provides the intended behavior independent from the Surefire flag.

**Comment by fenuks** [comment] 2023-02-02 15:08
Thank you for a very thorough answer. Given junit5 has been released over 4 years ago, it seems that surefire support might not be coming anytime soon/is complicated to do, I'll look into making a Spock extension, as you suggested.

**Comment by leonard84** [comment] 2023-02-13 20:17
As this is not a Spock issue I'll close it.

**Closed by leonard84** 2023-02-13 20:17 UTC
Labels: not a bug
