### ISSUE TITLE
Bad assertion message when using multi-line string literals with escaped initial new-line in assertion block

### ISSUE THREAD

**Issue by ddimtirov** [spockframework/spock#737] opened 2017-06-04 10:00 UTC
# Issue description

See the test case in [this gist](https://gist.github.com/ddimtirov/f1635ec9a77b8145ce10e52bef4e6047) - there are 3 identical tests comparing strings. All tests are working, as in failing and passing when they should.

The problem is that the assertion messages are bad for the variants that have a multi-line string literal with escaped initial new-line in the assertion block (regardless whether using `expect` or `then` block).

The gist also has example of a good and bad assertion messages.

# Additional Environment information
* IDEA 2017.2 EAP, Java 1.8u112, Windows 10
* [library versions](https://github.com/ddimtirov/nuggets/blob/1122ab6bb3c3f51ad86d250d396431875f2080b5/gradle/versions.gradle)

**Comment by dkhamitov** [comment] 2017-06-24 12:25
The problem is that ```unit.parse()```(at https://github.com/spockframework/spock/blob/131220df5b977e76573268fe9e9be337e494e39e/spock-core/src/main/java/org/spockframework/runtime/ExpressionInfoBuilder.java#L53) fails to parse the expression because it meets a single backslash (not followed by a new line, neither escaped). The purpose of a backslash here is to strip a new line, given that it is followed by a newline character. The possible solution (not the best, I suspect) is that If we can see this is the case in a spec, then we can just remove that single backslash and pass the safe expression to ```unit.parse()```

**Comment by leonard84** [comment] 2018-07-07 23:19
PR was merged closing

**Closed by leonard84** 2018-07-07 23:19 UTC
