### ISSUE TITLE
Spock fails to intercept certain bridge methods

### ISSUE THREAD

**Issue by facboy** [spockframework/spock#698] opened 2017-02-20 09:49 UTC
# Issue description

Under certain circumstances Spock intercept certain methods.  I haven't delved into it too deeply but it seems to be because they are 'bridge' methods.

# How to reproduce

Try to build this project: https://github.com/facboy/spock-bridge-bug

# Additional Environment information

## Java/JDK
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

## Groovy version
2.4.8

### Apache Maven
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /opt/java/apache-maven
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_121/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-514.6.1.el7.x86_64", arch: "amd64", family: "unix"

## Operating System
CentOS 7.3

## IDE
Intellij IDEA 2016.3.4

### Apache Maven
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.1-groovy-2.4-rc-3</version>
    </dependency>

**Comment by leonard84** [comment] 2017-02-21 10:14
Could you use ByteBuddy instead of cglib, it handles Bridge methods better. See discussion in #626 for details.

**Comment by facboy** [comment] 2017-02-21 11:18
We can't use byte buddy because of version incompatibilities.

**Comment by leonard84** [comment] 2017-02-22 18:04
@facboy the problem is that AFAIK cglib does not support bridge methods, maybe @raphw could add some more info.

**Comment by raphw** [comment] 2017-02-22 19:12
Due to `Parent` being package-private, javac adds a visibilty bridge to `Child`. cglib does not analyze generic types and can therefore not detect this. This cannot be solved with cglib. Byte Buddy does resolve the generic types and applies a class hierarchy analysis, therefore, it is able to handle this scenario.

**Comment by leonard84** [comment] 2017-02-23 17:00
@raphw thanks, I will close this issue since it is a problem of cglib and not on our side.

**Closed by leonard84** 2017-02-23 17:00 UTC
Labels: not a bug
