### ISSUE TITLE
No access to @Autowired variables in setupSpec() when using Spring's ContextConfiguration

### ISSUE THREAD

**Issue by robfletcher** [spockframework/spock#267] opened 2015-08-30 04:30 UTC
Originally reported on Google Code with ID 145

```
A spec that is annotated with @ContextConfiguration and uses @Autowired/@Inject cannot
access those injected beans in the setupSpec() or cleanupSpec() methods because they
just yield null.

reference example: 
http://code.google.com/p/spock/source/browse/trunk/spock-spring/src/test/groovy/org/spockframework/spring/TransactionalExample.groovy

as discussed in:
http://groups.google.com/group/spockframework/browse_thread/thread/22e15161529bace
```

Reported by `stephan.behnke` on 2010-11-16 11:32:53

**Comment by leonard84** [comment] 2021-06-04 13:23
Duplicate of #76 and fixed in Spock 2.0

**Closed by leonard84** 2021-06-04 13:23 UTC
Labels: Module-Core, Type-Defect
