### ISSUE TITLE
Possible scoping bug with @Unroll in Spock 1.2/1.3 and Groovy 2.5

### ISSUE THREAD

**Issue by DigitalZebra** [spockframework/spock#986] opened 2019-04-05 15:55 UTC
# Issue description
In Spock 1.3/Groovy 2.5, we are seeing an issue where having a typed variable of the same name as a test which uses `where/@Unroll` causes the scenario driven test to fail because of a typing issue. These specs don't fail with the Groovy 2.4 variants of Spock.

# How to reproduce
Here is a minimal spec that reproduces the issue in Spock 1.3/Groovy 2.5:
```
import spock.lang.Specification
import spock.lang.Unroll

class TestSpec extends Specification {

    def 'typed var same name'() {
        given:
        int myInteger = 5

        when:
        def actual = [foo: 5]

        then:
        assert actual.foo == myInteger
    }

    @Unroll
    def 'scenario with typedVar - #scenario'() {

        null == myInteger

        where:
        scenario | myInteger
        'null'   | null
    }
}
```

Running this test in either IntelliJ or with `./gradlew test` outputs the following error:
```
TestSpec > scenario with typedVar - #scenario FAILED
    org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'null' to class 'int'. Try 'java.lang.Integer' instead
        at TestSpec.scenario with typedVar - #scenario(TestSpec.groovy:23)
```

It appears to be trying to assign `null` to a variable of type `int`, which of course will fail. What doesn't make sense though is why `myInteger` is even defined as an `int` for the second test in the first place?

Using Spock 1.3 and Groovy 2.4 does not have the same behavior, and both tests pass. An addition workaround is to use `def` for declaring the `myInteger` variable instead of `int`.

## Link to a gist or similar (optional)
Here's a complete project that can be built/ran and show the issue:
https://github.com/DigitalZebra/spock-scope-bug

# Additional Environment information

## Java/JDK
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

## Groovy version
`2.5.4`

### Gradle
`4.10`

## Operating System
OSX

## IDE
IntelliJ

### Gradle/Grails
```
dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.5.4'

    testCompile "org.spockframework:spock-core:1.3-groovy-2.5"
}
```

**Comment by leonard84** [comment] 2019-04-05 18:09
This is a duplicate of #880 and the bug is in the groovy compiler, so there is not much we can do. Thanks for reporting non the less.

**Closed by leonard84** 2019-04-05 18:09 UTC
