### ISSUE TITLE
Unrolling a test only executes the first test.

### ISSUE THREAD

**Issue by Xaseron** [spockframework/spock#1070] opened 2020-01-09 09:20 UTC
# Issue description
Unrolling a test only executes the first test.
If i remove the `@Unroll` everything works.
If i remove the `#queryValue` from the method name everythings works.

# How to reproduce
```groovy
import spock.lang.Specification
import spock.lang.Unroll

class UnrollBugSpec extends Specification {

    @Unroll 
    void "Valid Mandatory QueryValue #queryValues"(String queryValues, Boolean returnStatus) {
        expect:
            assert returnStatus

        where:
            queryValues                                                        || returnStatus
            '?from=2018-12&to=2019-12'                                         || true
            '?from=2018-12&to=2019-12'                                         || true
            '?to=2019-12&from=2018-12&divisions=test&teams=test&products=test' || false
    }
}
```

# Additional Environment information
## Java/JDK
```
java -version
openjdk version "1.8.0_202"
OpenJDK Runtime Environment Corretto-8.202.08.2 (build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM Corretto-8.202.08.2 (build 25.202-b08, mixed mode)
```

## Groovy version
2.5

### Gradle
5.3

## Operating System
Windows

## IDE
IntelliJ

### Gradle/Grails
    testImplementation("org.spockframework:spock-core:1.3-groovy-2.5")

**Comment by szpak** [comment] 2020-01-09 09:42
I'm not able to reproduce the problem with your tests with `1.3-groovy-2.5` in Idea 2019.3.2 Preview:

![image](https://user-images.githubusercontent.com/148013/72056241-8851c980-32cc-11ea-94cc-c959cba2c6fa.png)

How to your run your tests?

Btw, you can remove `String queryValues, Boolean returnStatus` from the method arguments definition - they are not needed. The variables from `where` should be created by Spock AST and visible by IDE.

**Comment by Xaseron** [comment] 2020-01-09 10:39
If i create a new gradle project it works. But if copy the build.gradle from my project i can recreate the bug. i've added everything needed to this sample project https://github.com/Xaseron/UnrollBug

**Comment by Xaseron** [comment] 2020-01-09 11:21
You have to enable annotation processing to run this test in Intellij

**Comment by szpak** [comment] 2020-01-09 22:01
Thanks for the sample project. It definitely should not be required to enable annotation processing to be able to run a Spock test in Idea. As you have a lot of dependencies there, I propose to start removing them to determine which causes the aforementioned behavior (what breaks parameterized tests, in some scenarios).

**Comment by Xaseron** [comment] 2020-01-10 13:23
I have found the issue if i delete:
```gradle
test {
    useJUnitPlatform()
}
```
It executes all tests correctly. 
Is this related to Spock? 
We are not mixing JUnit and Spock tests so it would be safe to elave this dependecy out?

**Comment by Xaseron** [comment] 2020-01-10 13:48
I've updated the repo https://github.com/Xaseron/UnrollBug with a minimal `build.gradle.`
```gradle
plugins {
    id 'groovy'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.codehaus.groovy:groovy-all:2.5.6'
    testImplementation("org.spockframework:spock-core:1.3-groovy-2.5")
    testRuntimeOnly "org.junit.vintage:junit-vintage-engine:5.5.0"
}

test {
    useJUnitPlatform()
}
```

**Comment by Vampire** [comment] 2020-01-10 16:14
`useJUnitPlatform` means "Use JUnit 5", but Spock < v2 is based on JUnit 4.
I wonder there was anything executed at all, especially without using Vintage platform.
Spock v2 will be based on JUnit 5 instead.

**Comment by Xaseron** [comment] 2020-01-10 16:25
Is Vintage platform something different than `junit-vintage-engine`?

**Comment by Vampire** [comment] 2020-01-10 16:32
Oh, yeah, sorry, I was blind, forgot it is just a dependency. I thought you have to enable it too.

**Comment by szpak** [comment] 2020-01-12 14:42
@Xaseron Thanks for narrowing down the issue. Based on it I was able to determine what causes the problem - identical name of 2+ unrolled tests with `@Unroll` and `junit-vintage-engine`.

The following tests (in the aforementioned [sample project](https://github.com/Xaseron/UnrollBug/)) while running with JUnit Platform:
```
class UnrollBugSpec extends Specification {
    @Unroll
    void "Valid Mandatory QueryValue #queryValues"() {
        expect:
            assert returnStatus

        where:
            queryValues || returnStatus
            1           || true
            1           || true
            3           || false
    }
}
```
executes only one test - the first one.

What's "funny" with the following:
```
...
        where:
            queryValues || returnStatus
            1           || true
            3           || true
            3           || false
```
Gradle fails with:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Received a failure event for test with unknown id '30.4'. Registered test ids: '[:test, 30.2, 30.1]'
```
The problem occurs only with `junit-vintage-engine`. With JUnit 4.12 it works fine (3 tests are executed).

@marcphilipp Is there any extra filtering in `junit-vintage-engine` which may cause that?

**Comment by marcphilipp** [comment] 2020-02-17 19:23
Running the sample project with the JUnit Platform ConsoleLauncher shows that it's not an issue in the Vintage engine:

```
╷
├─ JUnit Vintage ✔
│  └─ UnrollBugSpec ✔
│     ├─ Valid Mandatory QueryValue ?from=2018-12&to=2019-12 ✔
│     ├─ Valid Mandatory QueryValue ?from=2018-12&to=2019-12 ✔
│     └─ Valid Mandatory QueryValue ?to=2019-12&from=2018-12&divisions=test&teams=test&pr... ✘ Condition not satisfied:
│           
│              returnStatus
│              |
│              false
└─ JUnit Jupiter ✔
```

**Comment by marcphilipp** [comment] 2020-02-17 19:28
Looks like my statement was a bit premature. When changing the inputs as suggested by @szpak above, JUnit Vintage seems to report the same unique ids which trips up Gradle:

```
╷
├─ JUnit Vintage
│  ├─ UnrollBugSpec
│  │       tags: []
│  │   uniqueId: [engine:junit-vintage]/[runner:UnrollBugSpec]
│  │     parent: [engine:junit-vintage]
│  │     source: ClassSource [className = 'UnrollBugSpec', filePosition = null]
│  ├─ Valid Mandatory QueryValue 1 dynamically registered
│  ├─ Valid Mandatory QueryValue 1
│  │       tags: []
│  │   uniqueId: [engine:junit-vintage]/[runner:UnrollBugSpec]/[dynamic:Valid Mandatory QueryValue 1(UnrollBugSpec)]
│  │     parent: [engine:junit-vintage]/[runner:UnrollBugSpec]
│  │     source: ClassSource [className = 'UnrollBugSpec', filePosition = null]
│  │   duration: 103 ms
│  │     status: ✔ SUCCESSFUL
│  ├─ Valid Mandatory QueryValue 3 dynamically registered
│  ├─ Valid Mandatory QueryValue 3
│  │       tags: []
│  │   uniqueId: [engine:junit-vintage]/[runner:UnrollBugSpec]/[dynamic:Valid Mandatory QueryValue 3(UnrollBugSpec)]
│  │     parent: [engine:junit-vintage]/[runner:UnrollBugSpec]
│  │     source: ClassSource [className = 'UnrollBugSpec', filePosition = null]
│  │   duration: 1 ms
│  │     status: ✔ SUCCESSFUL
│  ├─ Valid Mandatory QueryValue 3
│  │       tags: []
│  │   uniqueId: [engine:junit-vintage]/[runner:UnrollBugSpec]/[dynamic:Valid Mandatory QueryValue 3(UnrollBugSpec)]
│  │     parent: [engine:junit-vintage]/[runner:UnrollBugSpec]
│  │     source: ClassSource [className = 'UnrollBugSpec', filePosition = null]
│  │     caught: Condition not satisfied:
│  │               
│  │               returnStatus
│  │               |
│  │               false
│  │               
│  │               	at UnrollBugSpec.Valid Mandatory QueryValue #queryValues(UnrollBugSpec.groovy:9)
│  │   duration: 82 ms
│  │     status: ✘ FAILED
│  │   duration: 84 ms
│  │     status: ✔ SUCCESSFUL
└─ JUnit Vintage finished after 583 ms.
```

**Comment by marcphilipp** [comment] 2020-02-17 19:35
I'm afraid there's nothing the Vintage engine can do because the problem is that the `Description` objects it gets from Spock's JUnit 4 `Runner`, are exactly the same. If the goal is to fix this for Spock 1.x, we should provide a `uniqueId` (e.g. including the index) when creating the `Description` instance.

**Comment by marcphilipp** [comment] 2020-02-17 19:36
@Xaseron Is there an actual use case for two tests having the same name in your project?

**Comment by Vampire** [comment] 2020-02-17 19:40
Whether there is a valid use-case or not, this can very easily happen if you add data variables and do not add them to the pattern in some way, or first finish the test code before constructing a meaningful pattern.

**Comment by leonard84** [comment] 2020-02-17 19:40
I don't plan to release another 1.x bugfix release, as a workaround you can include `#iterationCount`, eg `Valid Mandatory QueryValue #queryValues [#iterationCount]`.

**Comment by Vampire** [comment] 2020-02-20 17:03
If you don't plan to release another 1.x release, I'd suggest to close this issue as wont-fix.
With Spock 2.0 there seems to be no problem if iterations have the same name.

**Comment by rojyates** [comment] 2020-04-09 06:39
> @Unroll
>     void "Valid Mandatory QueryValue #queryValues"() {

Just came across this and wondered if the use of `void` instead of `def` for the method declaration is causing duplicates names by suppressing the index Spock usually adds?

**Comment by Vampire** [comment] 2020-04-09 07:00
That doesn't matter. As soon as a pattern is given, the default pattern is not used anymore. Pattern can be given as argument to the unroll annotation, or if the method name contains at least one `#`. As soon as a pattern is given, the user is responsible for the naming.

**Closed** 2020-08-17 17:06 UTC
Labels: won't fix
