### ISSUE TITLE
Stub forgets about its overriden method in cleanup() method of JUnit test.

### ISSUE THREAD

**Issue by artieshevchenko** [spockframework/spock#809] opened 2018-01-13 20:23 UTC
In JUnit test (extends spock.lang.Specification) there are fields:

def realProvider
def presenceFinishInfoMock

They are initialized in:
setup() {
    realProvider = ...
    presenceFinishInfoMock = Stub(PresenceFinishInfo) {
      getProvider() >> realProvider
    }
}

During the test method execution realProvider is returned by getProvider() but in cleanup block presenceFinishInfoMock.getProvider() call returns "mock for type 'Provider' named 'dummy'". Verified that both times it's the same DynamicProxyMockInterceptorAdapter instance.

If I rename cleanup() to cleanup2() and call it manually at the end of the test method instead then realProvider is returned as expected.

**Environment:**

Intellij 2017.3.2 and Maven dependencies:

    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.1-groovy-2.4</version>
      <scope>test</scope>
    </dependency>
    
    <dependency> 
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.10</version>
    </dependency>
    <dependency> 
      <groupId>net.bytebuddy</groupId>
      <artifactId>byte-buddy</artifactId>
      <version>1.6.5</version>
      <scope>test</scope>
    </dependency>
    <dependency> 
      <groupId>org.objenesis</groupId>
      <artifactId>objenesis</artifactId>
      <version>2.5.1</version>
      <scope>test</scope>
    </dependency>

**Comment by leonard84** [comment] 2018-01-15 22:44
Duplicate of #795

**Closed by leonard84** 2018-01-15 22:44 UTC
Labels: not a bug
