### ISSUE TITLE
existance check of cglib versions greater than 2.2.2 fails

### ISSUE THREAD

**Issue by loesak** [spockframework/spock#686] opened 2017-01-18 17:58 UTC
# Issue description
When using versions of cglib-nodep versions greater than 2.2.2, ProxyBasedMockFactory fails to detect the existence of the library when attempting to mock a non-interface.

I figured that this would have been discovered already and being that I'm new to Spock, felt that the issue is likely with me but I could find no information of this anywhere and figured at least the provided example project from Spock would work but it doesn't.

# How to reproduce
Using Spocks own example project https://github.com/spockframework/spock-example, run `mvn clean verify` and watch the tests pass. However, no test is actually mocking out a non-interface class. Modify src/test/groovy/OrderedInteractionsSpec.groovy#Collaborator to be a class instead of an interface and then run `mvn clean verify` and get the following exception:

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.017 sec <<< FAILURE!
collaborators must be invoked in order(OrderedInteractionsSpec)  Time elapsed: 0.006 sec  <<< ERROR!
org.spockframework.mock.CannotCreateMockException: Cannot create mock for class Collaborator. Mocking of non-interface types requires the CGLIB library. Please put cglib-nodep-2.2 or higher on the class path.
        at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:52)
        at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:51)
        at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
        at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
        at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
        at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:83)
        at OrderedInteractionsSpec.collaborators must be invoked in order(OrderedInteractionsSpec.groovy:29)
```

When debugging, ProxyBasedMockFactory, value of cglibAvailable is false even though i can see the expected class (net.sf.cglib.proxy.Enhancer) in the cglib-nodep jar.

The only way i've gotten this to work with any version of cglib 3.x is to bring in the main cglib jar instead of cglib-nodep.

# Additional Environment information
command line and maven

## Java/JDK
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

**Comment by szpak** [comment] 2017-01-18 20:34
Can you check it with Spock 1.1(-rc-3)?

**Comment by loesak** [comment] 2017-01-18 21:45
That was one of the first things i tried as well as other variations of versions. The result were always the same without cglib 2.2.2. Below is my modified dependency section from the pom.xml. I updated spock, groovy, cglib, and objenesis to the latest versions.

```
  <dependencies>
    <!-- Mandatory dependencies for using Spock -->
    <dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <version>1.1-groovy-2.4-rc-3</version>
      <scope>test</scope>
    </dependency>
    <!-- Optional dependencies for using Spock -->
    <dependency> <!-- use a specific Groovy version rather than the one specified by spock-core -->
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.7</version>
    </dependency>
    <dependency> <!-- enables mocking of classes (in addition to interfaces) -->
      <groupId>cglib</groupId>
      <artifactId>cglib-nodep</artifactId>
      <version>3.2.4</version>
      <scope>test</scope>
    </dependency>
    <dependency> <!-- enables mocking of classes without default constructor (together with CGLIB) -->
      <groupId>org.objenesis</groupId>
      <artifactId>objenesis</artifactId>
      <version>2.5.1</version>
      <scope>test</scope>
    </dependency>
    <dependency> <!-- only required if Hamcrest matchers are used -->
      <groupId>org.hamcrest</groupId>
      <artifactId>hamcrest-core</artifactId>
      <version>1.3</version>
      <scope>test</scope>
    </dependency>
    <!-- Dependencies used by examples in this project (not required for using Spock) -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>1.4.185</version>
    </dependency>
  </dependencies>

```
and maven dependency:tree output
```
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spock Framework - Example Project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ spock-example ---
[INFO] org.spockframework:spock-example:jar:1.0-SNAPSHOT
[INFO] +- org.spockframework:spock-core:jar:1.1-groovy-2.4-rc-3:test
[INFO] |  \- junit:junit:jar:4.12:test
[INFO] +- org.codehaus.groovy:groovy-all:jar:2.4.7:compile
[INFO] +- cglib:cglib-nodep:jar:3.2.4:test
[INFO] +- org.objenesis:objenesis:jar:2.5.1:test
[INFO] +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- com.h2database:h2:jar:1.4.185:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.898 s
[INFO] Finished at: 2017-01-18T15:41:20-06:00
[INFO] Final Memory: 13M/304M
[INFO] ------------------------------------------------------------------------
```
and here is the maven execution output:
```
$ mvn clean verify
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Spock Framework - Example Project 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spock-example ---
[INFO] Deleting c:\Users\aaronl\git\spock-example\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spock-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\aaronl\git\spock-example\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ spock-example ---
[INFO] No sources to compile
[INFO]
[INFO] --- gmavenplus-plugin:1.4:compile (default) @ spock-example ---
[INFO] No sources specified for compilation.  Skipping.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spock-example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ spock-example ---
[INFO] No sources to compile
[INFO]
[INFO] --- gmavenplus-plugin:1.4:testCompile (default) @ spock-example ---
[INFO] Using Groovy 2.4.7 to perform testCompile.
[INFO] Compiled 25 files.
[INFO]
[INFO] --- maven-surefire-plugin:2.6:test (default-test) @ spock-example ---
[INFO] Surefire report directory: c:\Users\aaronl\git\spock-example\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running PublisherSpec
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.344 sec
Running EmptyStackSpec
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.034 sec
Running UsingJUnitRulesSpec
entering 'retrieve test name at runtime'
leaving 'retrieve test name at runtime'
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec
Running DatabaseDrivenSpec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.16 sec
Running StackWithThreeElementsSpec
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running StepwiseExtensionSpec
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running StackWithOneElementSpec
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec
Running HamcrestMatchersSpec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec
Running DataDrivenSpec
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.029 sec
Running OrderedInteractionsSpec
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.021 sec <<< FAILURE!
collaborators must be invoked in order(OrderedInteractionsSpec)  Time elapsed: 0.006 sec  <<< ERROR!
org.spockframework.mock.CannotCreateMockException: Cannot create mock for class Collaborator. Mocking of non-interface types requires a code generation library. Please put byte-buddy-1.4.0 or cglib-nodep-3.2 or higher on the class path.
        at org.spockframework.mock.runtime.ProxyBasedMockFactory.create(ProxyBasedMockFactory.java:69)
        at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:59)
        at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:40)
        at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
        at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:45)
        at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:281)
        at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:99)
        at OrderedInteractionsSpec.collaborators must be invoked in order(OrderedInteractionsSpec.groovy:27)

Running DerivedSpec
base setupSpec()
derived setupSpec()
base field initializer
derived field initializer
base setup()
derived setup()
base spec method
derived cleanup()
base cleanup()
base field initializer
derived field initializer
base setup()
derived setup()
derived spec method
derived cleanup()
base cleanup()
derived cleanupSpec()
base cleanupSpec()
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Running HelloSpockSpec
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec
Running IncludeExcludeExtensionSpec
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec

Results :

Tests in error:
  collaborators must be invoked in order(OrderedInteractionsSpec)

Tests run: 35, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.900 s
[INFO] Finished at: 2017-01-18T15:39:17-06:00
[INFO] Final Memory: 13M/297M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.6:test (default-test) on project spock-example: There are test failures.
[ERROR]
[ERROR] Please refer to c:\Users\aaronl\git\spock-example\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by leonard84** [comment] 2017-02-23 17:38
@loesak I could not reproduce your problem, could you cross check it with the gradlew build? Spock itself uses cglib-nodep so I don't think there is a problem.

**Comment by loesak** [comment] 2017-03-08 18:03
I can no longer reproduce the issue on a clean system so it must have been something else. However, i notice the tests are still not testing the mocking ability of a concrete implementation. Is that something worth adding?

**Comment by leonard84** [comment] 2017-03-09 20:43
@loesak what do you mean with

> the tests are still not testing the mocking ability of a concrete implementation. 

We run our tests both for cglib and bytebuddy.

**Comment by loesak** [comment] 2017-09-06 17:21
No where in any of the tests is `Mock()` being called on a class that is not a Java interface. For example from above, in the test `OrderedInteractionsSpec` on lines 27 and 28 creates two mocks of `Collaborator` which is not a concrete class but rather is an interface `interface Collaborator`. Mocking behavior is different if the thing being mocked is a concrete class implementation `class Collaborator`. This is how I originally broke the tests.

**Comment by leonard84** [comment] 2017-09-06 18:02
@loesak you are referring to the examples project only, right? I was referring to spock itself, see https://github.com/spockframework/spock/blob/068e573c45160a2ceabe70b18cbbfd9111a6e277/spock-specs/src/test/groovy/org/spockframework/smoke/mock/MockBasics.groovy#L103

However, there does not seem to been an issue so can you close it?

**Closed** 2017-09-21 21:10 UTC
Labels: cannot reproduce

**Comment by loesak** [comment] 2017-11-12 21:23
Yes, i was only referring to the examples project. I cannot reproduce the issue so closing is fine. Thank you
