### ISSUE TITLE
AST transformation messes up setter/getter in dot-property notation

### ISSUE THREAD

**Issue by kriegaex** [spockframework/spock#1158] opened 2020-05-06 02:33 UTC
I found [this on StackOverflow](https://stackoverflow.com/q/61599143/1082681). Here is my slightly modifed version of the sample code:

```groovy
package de.scrum_master.stackoverflow.q61599143

import spock.lang.Specification

class PropertyAccessTest extends Specification {
  def 'test setter on interface'() {
    given:
    def foo = Mock(Foo)
    when:
    foo.prop = 'val'
    then:
    1 * foo.setProp(_)
  }

  def 'test getter on interface'() {
    given:
    def foo = Mock(Foo)
    when:
    foo.prop
    then:
    1 * foo.getProp()
  }

  def 'test setter on abstract'() {
    given:
    def foo = Mock(FooBase)
    when:
    foo.prop = 'val'
    //foo.setProp('val')
    then:
    1 * foo.setProp(_)
    //1 * foo.setProperty('prop', 'val')
  }

  def 'test getter on abstract'() {
    given:
    def foo = Mock(FooBase)
    when:
    foo.prop
    //foo.getProp()
    then:
    1 * foo.getProp()
    //1 * foo.getProperty('prop')
  }

  def 'test setter on concrete'() {
    given:
    def foo = Mock(FooImpl)
    when:
    foo.prop = 'val'
    //foo.setProp('val')
    then:
    1 * foo.setProp(_)
    //1 * foo.setProperty('prop', 'val')
  }

  def 'test getter on concrete'() {
    given:
    def foo = Mock(FooImpl)
    when:
    foo.prop
    //foo.getProp()
    then:
    1 * foo.getProp()
    //1 * foo.getProperty('prop')
  }

  static interface Foo {
    String getProp()
    void setProp(String val)
  }

  static abstract class FooBase implements Foo {
    abstract String getProp();
    abstract void setProp(String val);
  }

  static class FooImpl extends FooBase {
    private String prop
    String getProp() {
      println('Foo.getProp')
      return prop
    }

    void setProp(String val) {
      println('Foo.setProp')
      this.prop = val
    }

    static void main(String[] args) {
      def fooImpl = new FooImpl()
      fooImpl.prop = "test1"
      println fooImpl.prop
      fooImpl.setProp("test2")
      println fooImpl.prop
    }
  }
}
```

Running this test in Spock 1.3-groovy-2.5 yields 4 failed tests:

```text
Too few invocations for:

1 * foo.setProp(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.setProperty('prop', 'val')
methodName == "setProp"
|          |
|          false
|          4 differences (63% similarity)
|          setProp(erty)
|          setProp(----)
setProperty

<too many arguments>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test setter on abstract(PropertyAccessTest.groovy:28)


Too few invocations for:

1 * foo.getProp()   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.getProperty('prop')
methodName == "getProp"
|          |
|          false
|          4 differences (63% similarity)
|          getProp(erty)
|          getProp(----)
getProperty

<no args expected>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test getter on abstract(PropertyAccessTest.groovy:39)


Too few invocations for:

1 * foo.setProp(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.setProperty('prop', 'val')
methodName == "setProp"
|          |
|          false
|          4 differences (63% similarity)
|          setProp(erty)
|          setProp(----)
setProperty

<too many arguments>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test setter on concrete(PropertyAccessTest.groovy:50)


Too few invocations for:

1 * foo.getProp()   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.getProperty('prop')
methodName == "getProp"
|          |
|          false
|          4 differences (63% similarity)
|          getProp(erty)
|          getProp(----)
getProperty

<no args expected>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test getter on concrete(PropertyAccessTest.groovy:61)
```

Running the exact same test on Spock 2.0-M2-groovy-3.0 yields only 2 failed tests:

```text
Too few invocations for:

1 * foo.setProp(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.setProperty('prop', 'val')
methodName == "setProp"
|          |
|          false
|          4 differences (63% similarity)
|          setProp(erty)
|          setProp(----)
setProperty

<too many arguments>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test setter on abstract(PropertyAccessTest.groovy:33)


Too few invocations for:

1 * foo.setProp(_)   (0 invocations)

Unmatched invocations (ordered by similarity):

1 * foo.setProperty('prop', 'val')
methodName == "setProp"
|          |
|          false
|          4 differences (63% similarity)
|          setProp(erty)
|          setProp(----)
setProperty

<too many arguments>
	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:98)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:77)
	at de.scrum_master.stackoverflow.q61599143.PropertyAccessTest.test setter on concrete(PropertyAccessTest.groovy:60)
```

Running the `main` method on both platforms shows that it is not a Groovy problem but probably related to a Spock AST transformation glitch:

```text
Foo.setProp
Foo.getProp
test1
Foo.setProp
Foo.getProp
test2
```

**Comment by haridsv** [comment] 2020-05-06 06:19
Thanks @kriegaex, appreciate you taking the time to confirm the bug in different versions as well as opening this bug.

**Comment by kriegaex** [comment] 2020-05-06 08:22
**Update:** Actually I just noticed that if the application classes are implemented in Java, it works as expected with the property notation for setters/getters. The problem seems to be related to `GroovyObject`s only.

**Comment by szpak** [comment] 2020-05-06 20:18
Thanks for your report with detailed use cases! It is a known reason I spotted working on Groovy 3 compatibility - #1076. There is a workaround (a hack) to handle common cases (for Groovy 3), but as it is not a problem which hits the majority of people, I would wait until https://issues.apache.org/jira/browse/GROOVY-9369 is fixed on the Groovy side.

**Comment by kriegaex** [comment] 2020-05-07 06:19
From the discussion in the other ticket and the ML it sounds as if this is purely a Groovy 3 problem, which it is not. On the contrary, more tests fail in Groovy 2 than in Groovy 3, but - as I said - only in Spock, not in pure Groovy. So to me it sounds as if even a future Groovy 3 fix will not help us on Spock 1.x with Groovy 2 or Spock 2.x with Groovy 2. I am not an AST expert, but my gut feeling tells me that this ought to be fixed in Spock. Maybe it can be analysed and differentiated in an AST phase earlier than the one used at the moment, i.e. before the AST has been transformed to a point where you can no longer differentiate what the user wrote in the source code and which intention she has.

**Comment by szpak** [comment] 2020-05-07 08:49
Please take a look at the [following code](https://github.com/spockframework/spock/blob/03818ed010f4b4ca1136a292e214f79d518c4abe/spock-core/src/main/java/org/spockframework/mock/runtime/JavaMockInterceptor.java#L55-L84) and again at my description in the [reported issue](https://issues.apache.org/jira/browse/GROOVY-9369) in Groovy. As the Groovy developers confirmed (on Slack) it could be a problem in 3.x and proposed to report the bug to take a look at it later on, I would prefer to avoid "additional hacks" to handle edge cases. However, I definitely could miss something, so if you have a good idea how to easily fix it (in a sensible way) on the Spock side please propose required changes.

**Comment by kriegaex** [comment] 2020-05-07 08:56
Actually I am just a Spock user and not a Groovy pro, so I am afraid cannot say anything intelligent about your code. But again the question: How can this be a Groovy 3 problem if it also happens in Groovy 2? My sample code and the provided logs prove it.

**Comment by szpak** [comment] 2020-05-07 09:15
Trying to fix the issues with Groovy 3, I also [spotted](https://github.com/spockframework/spock/pull/1075#discussion_r366788425) that some corner cases with mocking were already broken in the previous Spock versions with Groovy 2. Unfortunately, AFAIR I didn't have a good idea how to fix it without more "fragile hacks" (and it seems to be not very often used). Maybe it will be easier to cover in some sensible way at least for Groovy 3.

**Comment by kriegaex** [comment] 2020-05-07 09:24
What about my idea to look into it in an earlier AST phase an transform it into something unambiguous for the later phase Spock usually operates on? AFAIR Spock only works in one phase.

**Comment by bernhof** [comment] 2020-10-07 14:18
I'd like to add that this issue practically breaks all our stubs of classes with abstract superclasses. With a String property "bar" on object "foo", the following happens:
* `foo.bar` returns an object :disappointed: 
* `foo.getBar` returns the expected empty string

**Closed** 2020-10-27 21:42 UTC

**Comment by kriegaex** [comment] 2020-10-28 02:05
I just built master and the above specification `PropertyAccessTest` passes on my local machine now. Thank your very much.

_(Some other spec for parallel test execution failed on my Windows machine, but that is off-topic here.)_
