### ISSUE TITLE
Mock parameter type constraints do not work for primitive types

### ISSUE THREAD

**Issue by ddimtirov** [spockframework/spock#669] opened 2016-10-26 10:21 UTC
# Issue description

When we define a stub or mock on an API using method overloads differing by their primitive types, the argument type constraint needs to be specified as boxed type.
# How to reproduce

Consider the interface:

```
interface Foo {
  String bar(long x);
  String bar(double x);
}
```

The following mock will throw an error:

```
def foo = Mock(Foo) {
  _ * bar(_ as long) >> "Long"
  _ * bar(_ as double) >> "Double"
  0 * _
}

foo.bar(1L)
```

If we specify the constraints as boxed - it works:

```
def foo = Mock(Foo) {
  _ * bar(_ as Long) >> "Long"
  _ * bar(_ as Double) >> "Double"
  0 * _
}

foo.bar(1L)
```

But then what about this Java interface?

```
interface Foo {
  String bar(long x);
  String bar(Long x);
}
```
# Additional Environment information

Spock 1.0
## Java/JDK

1.8
## Groovy version

2.4.7

**Comment by angry-cellophane** [comment] 2016-11-07 23:15
Spock does nothing with it. Groovy does all the magic. 
From the official groovy [doc](http://docs.groovy-lang.org/latest/html/documentation/#_primitive_types):

> While Groovy declares and stores primitive fields and variables as primitives, because it uses Objects for everything, it autowraps references to primitives.

Another one example related to your issue - http://docs.groovy-lang.org/latest/html/documentation/core-differences-java.html#_primitives_and_wrappers.

So it's not a bug, it's a feature :)

**Comment by vairamsvsjdo** [comment] 2017-02-20 21:57
Please tag this as a question and close it.

**Closed** 2017-02-22 18:12 UTC
Labels: not a bug
