### ISSUE TITLE
Inner closure in the left side of assertion doesn't work

### ISSUE THREAD

**Issue by maksym-synkevych** [spockframework/spock#1299] opened 2021-03-16 22:10 UTC
# Issue description
During the update from 1.2-groovy-2.4 to 1.3-groovy-2.5, we faced with existing tests fail. 
At first sight, it seems that inner closure in the left side of assertion works on the Spock version 1.2-groovy-2.4 and does not work on version 1.3-groovy-2.5

# How to reproduce
Here is an example that can be used for testing purposes. This test passed under the Spock version 1.2-groovy-2.4 and did not pass under version 1.3-groovy-2.5.
```

import spock.lang.Specification
import spock.lang.Subject

class TestSpec extends Specification {

    def service1Mock = Mock(Service1)
    @Subject
    def service2 = new Service2(service1Mock)

    def "Test"() {
        given: "some data"
        def dtos = [new Dto("field1", "field2")]

        and: "mock service method"
        def expectedResult = dtos.first().field1 + dtos.first().field2
        1 * service1Mock.serviceMethod({ List<Dto> actualDtos ->
            verifyAll {
                actualDtos.collect { it.field1 } == [dtos.first().field1]
                actualDtos.collect { it.field2 } == [dtos.first().field2]
            }
            true
        }) >> expectedResult

        when: "call service2 serviceMethod"
        def actualResult = service2.serviceMethod(dtos)

        then:
        expectedResult == actualResult
    }

    class Service1 {

        def serviceMethod(List<Dto> dtos) {
            def dto = dtos.first()
            dto.field1 + dto.field2
        }
    }

    class Service2 {

        def service1

        Service2(Service1 service1) {
            this.service1 = service1
        }

        def serviceMethod(List<Dto> dtos) {
            service1.serviceMethod(dtos)
        }
    }

    class Dto {

        String field1
        String field2

        Dto(String field1, String field2) {
            this.field1 = field1
            this.field2 = field2
        }
    }
}

```

The test above passes if we extract `verifyAll` assertions in a separate method.

# Additional Environment information

## Java/JDK
`java -version`
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-bre_2020_11_16_15_09-b00)
OpenJDK 64-Bit Server VM (build 25.275-b00, mixed mode)

## Groovy version
`groovy -version`
Groovy Version: 3.0.7 JVM: 1.8.0_275 Vendor: Oracle Corporation OS: Mac OS X

### Apache Maven
`mvn -version`
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by leonard84** [comment] 2021-03-16 23:05
Duplicate of #994

**Closed by leonard84** 2021-03-16 23:05 UTC
