### ISSUE TITLE
Argument constraint possibly broken for collections

### ISSUE THREAD

**Issue by alesbukovsky** [spockframework/spock#1161] opened 2020-05-11 14:19 UTC
After upgrading to Spock 1.3 the following `then` clause stops working:
```
then: 
    1 * repo.saveSamples({
        it.size() == 2 &&
        it.find({ s -> s.getDay() == '2018-07-14' }).equals(new Sample('2018-07-14', 1)) &&
        it.find({ s -> s.getDay() == '2018-07-15' }).equals(new Sample('2018-07-15', 2))
    })
then:
    0 * repo._
```
The idea is to check that the `saveSamples()` method is called once with a list of 2 specific items. 

This code works just fine with Spock 1.2. I am aware of the changes in this area, but the similar pattern is used in other (simpler, no collection) cases without issue. Removing `&&` makes no difference. In either case I am not seeing any actual per-assertion feedback as mentioned in the Release Note. The only error I get is Too Many Invocations - in this case the error output indicates that the list passed into the call is in fact correct.

I am using Groovy 2.5 and also Spock Spring module.

**Comment by Vampire** [comment] 2020-05-11 14:50
Assuming this:
![grafik](https://user-images.githubusercontent.com/325196/81575466-5c903e80-93a7-11ea-9ea9-af0107247b92.png)
is just a typo here in the issue, not in your actual test,
did you try to set a breakpoint in the `it.size() == 2` line and see why the check is failing?

**Comment by alesbukovsky** [comment] 2020-05-11 16:10
Yes, that was a typo, sorry.

**Comment by Vampire** [comment] 2020-05-11 16:16
That I assumed, just mentioned it to double-check, how about the question? :-)

**Comment by alesbukovsky** [comment] 2020-05-11 16:23
I have set a breakpoint there and what I am getting is an exception on the first check with the collection (i.e. size check passes):
```
Condition not satisfied:

s.getDay() == '2018-07-14'
| |        |          |
| |        2018-07-15 false
| 2018-07-15          1 difference (90% similarity)
|                     2018-07-1(5)
|                     2018-07-1(4)
Sample(day=2018-07-15, id=2)
```
The list happens to be unsorted and 7/15 record is the first.

So it seems that the closure given to filter out the collection is actually treated as an assertion itself.

**Comment by Vampire** [comment] 2020-05-11 17:28
Hm, indeed looks like a bug from a quick look to the sources after AST transformation.
Here a more complete reproducer:
```groovy
  def test() {
    given:
    Repo repo = Mock()

    when:
    repo.saveSamples([new Sample('2018-07-15', 2), new Sample('2018-07-14', 1)])

    then:
    1 * repo.saveSamples({
      it.size() == 2 &&
        it.find({ s -> s.getDay() == '2018-07-14' }).equals(new Sample('2018-07-14', 1)) &&
        it.find({ s -> s.getDay() == '2018-07-15' }).equals(new Sample('2018-07-15', 2))
    })

    then:
    0 * repo._
  }

  static class Sample {
    String day
    int id

    Sample(String day, int id) {
      this.day = day
      this.id = id
    }

    boolean equals(o) {
      return (day == o.day) && (id == o.id)
    }

    @Override
    String toString() {
      return new StringJoiner(", ", Sample.class.getSimpleName() + "[", "]")
        .add("day='" + day + "'")
        .add("id=" + id)
        .toString();
    }
  }

  static class Repo {
    def saveSamples(List<Sample> samples) {
    }
  }
```

As "work-around" you could do it like this:
```groovy
    1 * repo.saveSamples({
      it.size() == 2
      it.contains new Sample('2018-07-14', 1)
      it.contains new Sample('2018-07-15', 2)
    })
```

With latest 2.0 master it is at least more obvious that something is heavily broken, it fails to compile due to twice duplicate `$spock_errorCollector` and `$spock_valueRecorder` definition.

**Comment by reftel** [comment] 2020-06-05 08:34
This is the same as #994 , right?

**Comment by Vampire** [comment] 2020-06-05 08:50
Sounds like it, yes

**Comment by leonard84** [comment] 2020-07-02 13:24
I'll close it since it is the same cause as 994

**Closed by leonard84** 2020-07-02 13:24 UTC
Labels: bug, duplicate
